[build-system]
requires = [
    "setuptools",
    "numpy",
    "scipy",
    "pandas",
    "scikit-image",
    "torch",
    "torchvision",
    "opencv-python"
    ]
build-backend = "setuptools.build_meta"